title: "archlinuxjp.github.io"
url: https://archlinuxjp.github.io

gems:
  - jekyll-redirect-from

# config
permalink: /:year/:month/:day/:title
exclude: ["CNAME", "config.rb", "Rakefile"]
paginate: 1
port: 8001
