baseurl = "https://archlinuxjp.github.io"
languageCode = "ja-jp"
title = "archlinuxjp"
copyright = "&copy; 2019. All rights reserved."
paginate = 10000

[permalinks]
post = "/post/:year/:month/:day/:slug"
archive = "/archive/:filename"
user = "/user/:filename"

[author]
name = "syui"

[params]
date_format = "2006-01-02"
mainSections = ["post"]

[markup.goldmark.renderer]
unsafe = true

[frontmatter]
date  = [":filename", ":default"]

[taxonomies]
tag = "tags"

[outputs]
home = ["JSON", "HTML"]
