name: github pages

on:
  push:
    branches:
    - source 

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Build
      run: |
           hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
